"""
Language definitions for GCode 3D Viewer.
10+ languages supported.
"""

# Base English strings - all other languages copy from this
_BASE = {
    'name': 'English',
    'file': 'File',
    'open_file': 'Open File...',
    'save_screenshot': 'Save Screenshot...',
    'save_thumbnail': 'Save Thumbnail...',
    'exit': 'Exit',
    'view': 'View',
    'reset_view': 'Reset View',
    'view_top': 'View: Top',
    'view_front': 'View: Front',
    'view_side': 'View: Side',
    'zoom_in': 'Zoom In',
    'zoom_out': 'Zoom Out',
    'show_travel': 'Show Travel Moves',
    'thumbnail': 'Thumbnail',
    'view_thumbnail': 'View Embedded Thumbnail',
    'settings': 'Settings',
    'language': 'Language',
    'theme': 'Theme',
    'theme_dark': 'Dark',
    'theme_light': 'Light',
    'help': 'Help',
    'shortcuts': 'Keyboard Shortcuts',
    'about': 'About',
    'file_info': 'File',
    'layer': 'Layer',
    'options': 'Options',
    'show_travel_cb': 'Show Travel',
    'statistics': 'Statistics',
    'controls': 'Controls',
    'ctrl_rotate': 'Left drag = Rotate',
    'ctrl_pan': 'Right drag = Pan',
    'ctrl_zoom': 'Scroll = Zoom',
    'ctrl_reset': 'R = Reset view',
    'ctrl_open': 'Ctrl+O = Open file',
    'no_file': 'No file opened',
    'ready': 'Ready — Drag & drop .gcode or use File > Open',
    'dnd_active': 'Drag & Drop: Active',
    'dnd_inactive': 'Drag & Drop: N/A',
    'loading': 'Loading',
    'parsing': 'Parsing',
    'no_path': 'No path in',
    'no_path_msg': 'File has no G0/G1 moves.',
    'unsupported_fmt': 'Unsupported Format',
    'unsupported_msg': "Not a GCode file.\nSupported: .gcode, .gco, .g",
    'file_not_found': 'File not found',
    'no_model': 'No model loaded.',
    'saved_to': 'Saved to:\n{}',
    'no_thumbnail': 'No embedded thumbnail.\nEnable in slicer settings.',
    'thumb_error': 'Cannot open thumbnail: {}',
    'success': 'Success',
    'info': 'Info',
    'error': 'Error',
    'warning': 'Warning',
    'placeholder': "Drag & drop .gcode here\nor File > Open\n\nLeft drag = Rotate\nRight drag = Pan\nScroll = Zoom",
    'layers_lbl': 'Layers',
    'segments_lbl': 'Segments',
    'extrude_lbl': 'Extrude',
    'travel_lbl': 'Travel',
    'thumb_lbl': 'Thumbnail',
    'yes': 'Yes',
    'no': 'No',
    'restart_msg': 'Restart app for full language change.',
}

LANGUAGES = {
    'en': {**_BASE},
    'id': {
        **_BASE,
        'name': 'Bahasa Indonesia',
        'open_file': 'Buka File...',
        'save_screenshot': 'Simpan Screenshot...',
        'save_thumbnail': 'Simpan Thumbnail...',
        'exit': 'Keluar',
        'view': 'Tampilan',
        'reset_view': 'Reset Tampilan',
        'view_top': 'Tampilan: Atas',
        'view_front': 'Tampilan: Depan',
        'view_side': 'Tampilan: Samping',
        'zoom_in': 'Perbesar',
        'zoom_out': 'Perkecil',
        'show_travel': 'Tampilkan Travel',
        'view_thumbnail': 'Lihat Thumbnail',
        'settings': 'Pengaturan',
        'language': 'Bahasa',
        'theme': 'Tema',
        'theme_dark': 'Gelap',
        'theme_light': 'Terang',
        'help': 'Bantuan',
        'shortcuts': 'Pintasan Keyboard',
        'about': 'Tentang',
        'file_info': 'File',
        'options': 'Opsi',
        'show_travel_cb': 'Tampilkan Travel',
        'statistics': 'Statistik',
        'controls': 'Kontrol',
        'ctrl_rotate': 'Kiri drag = Rotasi',
        'ctrl_pan': 'Kanan drag = Pan',
        'ctrl_reset': 'R = Reset tampilan',
        'ctrl_open': 'Ctrl+O = Buka file',
        'no_file': 'Belum ada file',
        'ready': 'Siap — Drag & drop .gcode atau File > Buka',
        'dnd_active': 'Drag & Drop: Aktif',
        'dnd_inactive': 'Drag & Drop: Tidak tersedia',
        'loading': 'Memuat',
        'no_path': 'Tidak ada path di',
        'no_path_msg': 'File tidak ada gerakan G0/G1.',
        'unsupported_fmt': 'Format Tidak Didukung',
        'unsupported_msg': "Bukan file GCode.\nDidukung: .gcode, .gco, .g",
        'file_not_found': 'File tidak ditemukan',
        'no_model': 'Belum ada model.',
        'saved_to': 'Disimpan ke:\n{}',
        'no_thumbnail': 'Tidak ada thumbnail.\nAktifkan di pengaturan slicer.',
        'thumb_error': 'Gagal buka thumbnail: {}',
        'success': 'Berhasil',
        'warning': 'Peringatan',
        'placeholder': "Drag & drop .gcode ke sini\natau File > Buka\n\nKiri drag = Rotasi\nKanan drag = Pan\nScroll = Zoom",
        'yes': 'Ya',
        'no': 'Tidak',
        'restart_msg': 'Restart aplikasi untuk perubahan bahasa.',
    },
    'zh': {
        **_BASE,
        'name': '中文',
        'open_file': '打开文件...',
        'save_screenshot': '保存截图...',
        'save_thumbnail': '保存缩略图...',
        'exit': '退出',
        'view': '视图',
        'reset_view': '重置视图',
        'view_top': '视图: 顶部',
        'view_front': '视图: 正面',
        'view_side': '视图: 侧面',
        'zoom_in': '放大',
        'zoom_out': '缩小',
        'show_travel': '显示空走',
        'view_thumbnail': '查看缩略图',
        'settings': '设置',
        'language': '语言',
        'theme': '主题',
        'theme_dark': '深色',
        'theme_light': '浅色',
        'help': '帮助',
        'shortcuts': '快捷键',
        'about': '关于',
        'file_info': '文件',
        'options': '选项',
        'show_travel_cb': '显示空走',
        'statistics': '统计',
        'controls': '控制',
        'ctrl_rotate': '左键拖动 = 旋转',
        'ctrl_pan': '右键拖动 = 平移',
        'ctrl_zoom': '滚轮 = 缩放',
        'ctrl_reset': 'R = 重置视图',
        'ctrl_open': 'Ctrl+O = 打开',
        'no_file': '未打开文件',
        'ready': '就绪 — 拖放 .gcode 或 文件 > 打开',
        'dnd_active': '拖放: 可用',
        'dnd_inactive': '拖放: 不可用',
        'loading': '加载中',
        'parsing': '解析中',
        'no_path': '无路径',
        'no_path_msg': '文件无G0/G1移动。',
        'unsupported_fmt': '不支持的格式',
        'unsupported_msg': "非GCode文件。\n支持: .gcode, .gco, .g",
        'file_not_found': '文件未找到',
        'no_model': '未加载模型。',
        'saved_to': '已保存到:\n{}',
        'no_thumbnail': '无嵌入缩略图。\n请在切片器中启用。',
        'success': '成功',
        'warning': '警告',
        'placeholder': "拖放 .gcode 到此处\n或 文件 > 打开\n\n左键拖动 = 旋转\n右键拖动 = 平移\n滚轮 = 缩放",
        'yes': '是',
        'no': '否',
        'restart_msg': '重启应用以完全切换语言。',
    },
    'ja': {
        **_BASE,
        'name': '日本語',
        'open_file': 'ファイルを開く...',
        'save_screenshot': 'スクリーンショット保存...',
        'save_thumbnail': 'サムネイル保存...',
        'exit': '終了',
        'view': '表示',
        'reset_view': 'ビューリセット',
        'view_top': '表示: 上面',
        'view_front': '表示: 正面',
        'view_side': '表示: 側面',
        'zoom_in': '拡大',
        'zoom_out': '縮小',
        'show_travel': 'トラベル表示',
        'view_thumbnail': 'サムネイル表示',
        'settings': '設定',
        'language': '言語',
        'theme': 'テーマ',
        'theme_dark': 'ダーク',
        'theme_light': 'ライト',
        'help': 'ヘルプ',
        'shortcuts': 'ショートカット',
        'about': 'について',
        'file_info': 'ファイル',
        'options': 'オプション',
        'show_travel_cb': 'トラベル表示',
        'statistics': '統計',
        'controls': '操作',
        'ctrl_rotate': '左ドラッグ = 回転',
        'ctrl_pan': '右ドラッグ = パン',
        'ctrl_zoom': 'スクロール = ズーム',
        'ctrl_reset': 'R = リセット',
        'ctrl_open': 'Ctrl+O = 開く',
        'no_file': 'ファイル未選択',
        'ready': '準備完了 — .gcodeをドロップまたはファイル > 開く',
        'loading': '読み込み中',
        'parsing': '解析中',
        'placeholder': ".gcodeをここにドロップ\nまたはファイル > 開く\n\n左ドラッグ = 回転\n右ドラッグ = パン\nスクロール = ズーム",
        'restart_msg': '言語変更を完全に適用するにはアプリを再起動してください。',
    },
    'ko': {
        **_BASE,
        'name': '한국어',
        'open_file': '파일 열기...',
        'save_screenshot': '스크린샷 저장...',
        'save_thumbnail': '썸네일 저장...',
        'exit': '종료',
        'view': '보기',
        'reset_view': '뷰 초기화',
        'view_top': '보기: 위',
        'view_front': '보기: 앞',
        'view_side': '보기: 옆',
        'zoom_in': '확대',
        'zoom_out': '축소',
        'show_travel': '이동 표시',
        'view_thumbnail': '썸네일 보기',
        'settings': '설정',
        'language': '언어',
        'theme': '테마',
        'theme_dark': '다크',
        'theme_light': '라이트',
        'help': '도움말',
        'shortcuts': '단축키',
        'about': '정보',
        'no_file': '파일 없음',
        'ready': '준비 — .gcode를 드롭하거나 파일 > 열기',
        'placeholder': ".gcode를 여기에 드롭\n또는 파일 > 열기\n\n좌클릭 드래그 = 회전\n우클릭 드래그 = 이동\n스크롤 = 줌",
        'restart_msg': '언어 변경을 위해 앱을 재시작하세요.',
    },
    'de': {
        **_BASE,
        'name': 'Deutsch',
        'open_file': 'Datei öffnen...',
        'save_screenshot': 'Screenshot speichern...',
        'save_thumbnail': 'Thumbnail speichern...',
        'exit': 'Beenden',
        'view': 'Ansicht',
        'reset_view': 'Ansicht zurücksetzen',
        'view_top': 'Ansicht: Oben',
        'view_front': 'Ansicht: Vorne',
        'view_side': 'Ansicht: Seite',
        'zoom_in': 'Vergrößern',
        'zoom_out': 'Verkleinern',
        'show_travel': 'Fahrbewegungen anzeigen',
        'view_thumbnail': 'Thumbnail anzeigen',
        'settings': 'Einstellungen',
        'language': 'Sprache',
        'theme': 'Design',
        'theme_dark': 'Dunkel',
        'theme_light': 'Hell',
        'help': 'Hilfe',
        'shortcuts': 'Tastenkürzel',
        'about': 'Über',
        'options': 'Optionen',
        'statistics': 'Statistik',
        'controls': 'Steuerung',
        'no_file': 'Keine Datei geöffnet',
        'ready': 'Bereit — .gcode hierher ziehen oder Datei > Öffnen',
        'placeholder': ".gcode hierher ziehen\noder Datei > Öffnen\n\nLinks ziehen = Drehen\nRechts ziehen = Verschieben\nScrollen = Zoom",
        'restart_msg': 'App neu starten für Sprachwechsel.',
    },
    'fr': {
        **_BASE,
        'name': 'Français',
        'open_file': 'Ouvrir fichier...',
        'save_screenshot': 'Enregistrer capture...',
        'save_thumbnail': 'Enregistrer miniature...',
        'exit': 'Quitter',
        'view': 'Affichage',
        'reset_view': 'Réinitialiser la vue',
        'view_top': 'Vue: Dessus',
        'view_front': 'Vue: Face',
        'view_side': 'Vue: Côté',
        'zoom_in': 'Zoom avant',
        'zoom_out': 'Zoom arrière',
        'show_travel': 'Afficher déplacements',
        'view_thumbnail': 'Voir miniature',
        'settings': 'Paramètres',
        'language': 'Langue',
        'theme': 'Thème',
        'theme_dark': 'Sombre',
        'theme_light': 'Clair',
        'help': 'Aide',
        'shortcuts': 'Raccourcis clavier',
        'about': 'À propos',
        'options': 'Options',
        'statistics': 'Statistiques',
        'controls': 'Contrôles',
        'no_file': 'Aucun fichier ouvert',
        'ready': 'Prêt — Glisser .gcode ou Fichier > Ouvrir',
        'placeholder': "Glisser .gcode ici\nou Fichier > Ouvrir\n\nClic gauche = Rotation\nClic droit = Déplacer\nMolette = Zoom",
        'restart_msg': "Redémarrer l'app pour changer la langue.",
    },
    'es': {
        **_BASE,
        'name': 'Español',
        'open_file': 'Abrir archivo...',
        'save_screenshot': 'Guardar captura...',
        'save_thumbnail': 'Guardar miniatura...',
        'exit': 'Salir',
        'view': 'Vista',
        'reset_view': 'Restablecer vista',
        'view_top': 'Vista: Arriba',
        'view_front': 'Vista: Frente',
        'view_side': 'Vista: Lado',
        'zoom_in': 'Acercar',
        'zoom_out': 'Alejar',
        'show_travel': 'Mostrar viajes',
        'view_thumbnail': 'Ver miniatura',
        'settings': 'Configuración',
        'language': 'Idioma',
        'theme': 'Tema',
        'theme_dark': 'Oscuro',
        'theme_light': 'Claro',
        'help': 'Ayuda',
        'shortcuts': 'Atajos de teclado',
        'about': 'Acerca de',
        'options': 'Opciones',
        'statistics': 'Estadísticas',
        'controls': 'Controles',
        'no_file': 'Sin archivo',
        'ready': 'Listo — Arrastrar .gcode o Archivo > Abrir',
        'placeholder': "Arrastrar .gcode aquí\no Archivo > Abrir\n\nClic izq = Rotar\nClic der = Mover\nScroll = Zoom",
        'restart_msg': 'Reiniciar app para cambiar idioma.',
    },
    'pt': {
        **_BASE,
        'name': 'Português',
        'open_file': 'Abrir arquivo...',
        'save_screenshot': 'Salvar captura...',
        'save_thumbnail': 'Salvar miniatura...',
        'exit': 'Sair',
        'view': 'Visualizar',
        'reset_view': 'Redefinir vista',
        'view_top': 'Vista: Topo',
        'view_front': 'Vista: Frente',
        'view_side': 'Vista: Lado',
        'zoom_in': 'Ampliar',
        'zoom_out': 'Reduzir',
        'show_travel': 'Mostrar viagens',
        'view_thumbnail': 'Ver miniatura',
        'settings': 'Configurações',
        'language': 'Idioma',
        'theme': 'Tema',
        'theme_dark': 'Escuro',
        'theme_light': 'Claro',
        'help': 'Ajuda',
        'shortcuts': 'Atalhos',
        'about': 'Sobre',
        'no_file': 'Nenhum arquivo',
        'ready': 'Pronto — Arraste .gcode ou Arquivo > Abrir',
        'placeholder': "Arraste .gcode aqui\nou Arquivo > Abrir\n\nEsquerdo = Rotação\nDireito = Mover\nScroll = Zoom",
        'restart_msg': 'Reinicie o app para mudar o idioma.',
    },
    'ru': {
        **_BASE,
        'name': 'Русский',
        'open_file': 'Открыть файл...',
        'save_screenshot': 'Сохранить скриншот...',
        'save_thumbnail': 'Сохранить миниатюру...',
        'exit': 'Выход',
        'view': 'Вид',
        'reset_view': 'Сбросить вид',
        'view_top': 'Вид: Сверху',
        'view_front': 'Вид: Спереди',
        'view_side': 'Вид: Сбоку',
        'zoom_in': 'Увеличить',
        'zoom_out': 'Уменьшить',
        'show_travel': 'Показать перемещения',
        'view_thumbnail': 'Показать миниатюру',
        'settings': 'Настройки',
        'language': 'Язык',
        'theme': 'Тема',
        'theme_dark': 'Тёмная',
        'theme_light': 'Светлая',
        'help': 'Помощь',
        'shortcuts': 'Горячие клавиши',
        'about': 'О программе',
        'options': 'Параметры',
        'statistics': 'Статистика',
        'controls': 'Управление',
        'no_file': 'Файл не открыт',
        'ready': 'Готово — Перетащите .gcode или Файл > Открыть',
        'placeholder': "Перетащите .gcode сюда\nили Файл > Открыть\n\nЛевая = Вращение\nПравая = Перемещение\nКолесо = Масштаб",
        'restart_msg': 'Перезапустите для смены языка.',
    },
    'tr': {
        **_BASE,
        'name': 'Türkçe',
        'open_file': 'Dosya Aç...',
        'save_screenshot': 'Ekran Görüntüsü Kaydet...',
        'save_thumbnail': 'Küçük Resim Kaydet...',
        'exit': 'Çıkış',
        'view': 'Görünüm',
        'reset_view': 'Görünümü Sıfırla',
        'view_top': 'Görünüm: Üst',
        'view_front': 'Görünüm: Ön',
        'view_side': 'Görünüm: Yan',
        'zoom_in': 'Yakınlaştır',
        'zoom_out': 'Uzaklaştır',
        'show_travel': 'Hareketleri Göster',
        'view_thumbnail': 'Küçük Resmi Göster',
        'settings': 'Ayarlar',
        'language': 'Dil',
        'theme': 'Tema',
        'theme_dark': 'Koyu',
        'theme_light': 'Açık',
        'help': 'Yardım',
        'shortcuts': 'Kısayollar',
        'about': 'Hakkında',
        'no_file': 'Dosya açılmadı',
        'ready': 'Hazır — .gcode sürükle veya Dosya > Aç',
        'placeholder': ".gcode dosyasını buraya sürükle\nveya Dosya > Aç\n\nSol sürükle = Döndür\nSağ sürükle = Kaydır\nTekerlek = Yakınlaştır",
        'restart_msg': 'Dil değişikliği için uygulamayı yeniden başlatın.',
    },
    'it': {
        **_BASE,
        'name': 'Italiano',
        'open_file': 'Apri file...',
        'save_screenshot': 'Salva screenshot...',
        'save_thumbnail': 'Salva miniatura...',
        'exit': 'Esci',
        'view': 'Visualizza',
        'reset_view': 'Reimposta vista',
        'view_top': 'Vista: Alto',
        'view_front': 'Vista: Fronte',
        'view_side': 'Vista: Lato',
        'zoom_in': 'Ingrandisci',
        'zoom_out': 'Riduci',
        'show_travel': 'Mostra spostamenti',
        'view_thumbnail': 'Mostra miniatura',
        'settings': 'Impostazioni',
        'language': 'Lingua',
        'theme': 'Tema',
        'theme_dark': 'Scuro',
        'theme_light': 'Chiaro',
        'help': 'Aiuto',
        'shortcuts': 'Scorciatoie',
        'about': 'Informazioni',
        'no_file': 'Nessun file aperto',
        'ready': 'Pronto — Trascina .gcode o File > Apri',
        'placeholder': "Trascina .gcode qui\no File > Apri\n\nSinistro = Ruota\nDestro = Sposta\nRotella = Zoom",
        'restart_msg': "Riavvia l'app per cambiare lingua.",
    },
}


def get_text(lang_code, key):
    """Get translated text. Falls back to English."""
    lang = LANGUAGES.get(lang_code, LANGUAGES['en'])
    return lang.get(key, LANGUAGES['en'].get(key, key))
